In [79]:
import numpy as np

In [80]:
a1 = np.arange(1,13).reshape(3,4)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
mask1 = a1<6
print(a1[mask1])

[1 2 3 4 5]


In [82]:
mask2 = a1 == 2
print(a1[mask2])

[2]


In [83]:
mask3 = (a1<3) | (a1>6)
mask4 = (a1>3) & (a1<6)
print(a1[mask3],"\n")
print(a1[mask4])

[ 1  2  7  8  9 10 11 12] 

[4 5]


In [84]:
a2 = a1+8
print(a2)

[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [85]:
a3 = np.arange(1,13).reshape(3,4)
a4 = np.arange(1,13).reshape(3,4)
print(a3 == a4)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [86]:
a3 = np.arange(1,13).reshape(3,4)
a4 = np.arange(1,13).reshape(4,3)
print(a3 == a4)

False


/var/folders/qf/b_1clwxx1f11gyqwhwkz9lrh0000gn/T/ipykernel_19399/3214156684.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(a3 == a4)


In [87]:
a5 = np.array([1,2,3,4,5])
a6 = np.array([9,4,5,3,2])
print(a5>a6,"\n")
print(a6>a5)

[False False False  True  True] 

[ True  True  True False False]


In [88]:
a7 = np.arange(1,13).reshape(3,4)
print(a7,"\n")
a7[a7<6] = 0
print(a7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 0  0  0  0]
 [ 0  6  7  8]
 [ 9 10 11 12]]


In [89]:
a8 = np.array([0,1,2,3,4,5,6,7,8,9])
print(a8,"\n")
mask5 = a8%2 == 0
a8[mask5] = 19
print(a8)

[0 1 2 3 4 5 6 7 8 9] 

[19  1 19  3 19  5 19  7 19  9]


In [90]:
a5 = np.array([1,2,3,4,5])
a6 = np.array([9,4,5,3,2])
print(a5+a6)
print(np.add(a5,a6))
np.divide(a5,a6)

[10  6  8  7  7]
[10  6  8  7  7]


array([0.11111111, 0.5       , 0.6       , 1.33333333, 2.5       ])

In [91]:
a3 = np.arange(1,13).reshape(3,4)
a4 = np.arange(1,13).reshape(3,4)
print(a3+a4)
np.add(a3,a4)
np.divide(a3,a4)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
print(np.sum(a3))
print(np.sum(a5))

78
15


In [93]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [94]:
arr1=np.array(['Ram','Astha','Brahat'])
arr2=np.array(['Shyam','Kalyan','Naveen'])
arr1>arr2

array([False, False, False])

In [102]:
a6 = np.arange(1,13).reshape(3,4)
print(a6,"\n")
print(np.sum(a6),"\n")
print(np.sum(a6,axis=1),"\n")
print(np.sum(a6,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

78 

[10 26 42] 

[15 18 21 24]


In [106]:
a6.sum()

78

In [107]:
a6[:,0].sum()

15

In [108]:
np.sum(a6[0,:])

10

In [127]:
a7 = np.arange(1,13).reshape(3,4)
print(a7,"\n")
print(np.mean(a7,axis = 0),"\n")
print(np.mean(a7,axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[5. 6. 7. 8.] 

[ 2.5  6.5 10.5]


In [130]:
print(np.mean(a7[0],axis = 0))

2.5


In [197]:
a7 = np.arange(1,13).reshape(3,4)
print(np.mean(a7[:,0],axis = 0))

5.0


In [142]:
np.max(a7,axis = 0)

array([ 9, 10, 11, 12])

In [143]:
np.max(a7,axis = 1)

array([ 4,  8, 12])

In [144]:
np.min(a7,axis = 1)

array([1, 5, 9])

In [145]:
np.min(a7,axis = 0)

array([1, 2, 3, 4])

In [146]:
a8 = np.array([0,1,0])
np.any(a8)

True

In [148]:
a8 = np.array([0,0,0])
np.any(a8)# Return true if any non zero value is presnet

False

In [150]:
a8 = np.array([2,4,8])
a9 = np.array([4,5,6])
print(a8<a9)

[ True  True False]


In [151]:
print(a9<a8)

[False False  True]


In [152]:
print(np.any(a9<a8)) #Return true if any non zero(True) value is present. True is present

True


In [153]:
a10 = np.array([False,False,False])
print(np.any(a10))

False


In [154]:
a10 = np.array([False,False,True])
print(np.any(a10))

True


In [156]:
print(np.any(a9%2 == 0))

True


In [157]:
b1 = np.array([8,6,54,3,4,5,7,8,1])
b2 = np.array([2,5,6,7,8,9,0,7,6])
np.all(b1<b2)

False

In [158]:
np.all(b1>b2)

False

In [167]:
b1 = np.array([8,6,5,3,4,5,7,8,1])
b2 = np.array([1,2,3,2,3,0,1,2,0])
np.all(b1<b2)

False

In [168]:
np.all(b1>b2)

True

In [171]:
np.all((b1<b2) | (b2<b1))

True

In [173]:
b3 = np.array([8,9,6,7,85,6,7,5,6,5,3,0])
b3.sort()
print(b3)

[ 0  3  5  5  6  6  6  7  7  8  9 85]


In [175]:
b3 = np.array([8,9,6,7,85,6,7,5,6,5,3,0])
print(b3,"\n")
print(np.sort(b3))

[ 8  9  6  7 85  6  7  5  6  5  3  0] 

[ 0  3  5  5  6  6  6  7  7  8  9 85]


In [176]:
np.argsort(b3)# Return index of sorted array(arg gives index)

array([11, 10,  7,  9,  2,  5,  8,  3,  6,  0,  1,  4])

In [180]:
b4 = np.array([[6,1,7,0,5,9],[2,4,2,5,6,8],[9,8,6,5,3,2]])
print(b4,"\n")
print(np.sort(b4),"\n")
print(np.argsort(b4))

[[6 1 7 0 5 9]
 [2 4 2 5 6 8]
 [9 8 6 5 3 2]] 

[[0 1 5 6 7 9]
 [2 2 4 5 6 8]
 [2 3 5 6 8 9]] 

[[3 1 4 0 2 5]
 [0 2 1 3 4 5]
 [5 4 3 2 1 0]]


In [192]:
b4 = np.array([[6,1,7,0,5,9],[2,4,2,5,6,8],[9,8,6,5,3,2]])
print(b4,"\n")
b5 = np.sort(b4,axis = 1)
print(b5,"\n")
print(np.argsort(b5))#Return index of the sort array for axis 1(always return index in this format)

[[6 1 7 0 5 9]
 [2 4 2 5 6 8]
 [9 8 6 5 3 2]] 

[[0 1 5 6 7 9]
 [2 2 4 5 6 8]
 [2 3 5 6 8 9]] 

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [193]:
np.sort(b4,axis = 0)

array([[2, 1, 2, 0, 3, 2],
       [6, 4, 6, 5, 5, 8],
       [9, 8, 7, 5, 6, 9]])