In [1]:
import numpy as np
import math

In [2]:
a1 = np.arange(1,5).reshape((2,2))
print(a1 + 2,"\n")
print(a1 * 3)

[[3 4]
 [5 6]] 

[[ 3  6]
 [ 9 12]]


In [3]:
a2 = np.array([[2,3,4],[4,5,6]])
a3 = np.array([[7,2,1],[7,6,9],[3,4,5]])
np.dot(a2,a3)#Matrix multiplication

array([[47, 38, 49],
       [81, 62, 79]])

In [4]:
np.matmul(a2,a3)

array([[47, 38, 49],
       [81, 62, 79]])

In [5]:
a2@a3

array([[47, 38, 49],
       [81, 62, 79]])

In [6]:
a4 = np.arange(1,13).reshape((3,4))
print(a4,"\n")
func = np.vectorize(math.log)#Create personalise function and can pass it.
#It will print all the log value of a4 array nos
x = func(a4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]


In [7]:
#Tile

In [8]:
a5 = np.arange(1,13).reshape((3,4))
print(a5,"\n")
np.tile(a5,(2,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [9]:
a6 = np.arange(1,13)
print(a6,"\n")
print(np.split(a6,2),"\n")#use for equal split. Depends the no of splits wants to do. here its 2
print(np.split(a6,3),"\n")
print(np.split(a6,5))# Failed because 12 can't be divided by 5

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])] 

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])] 



ValueError: array split does not result in an equal division

In [10]:
#For unequal split

In [11]:
a6 = np.arange(1,13)
print(a6,"\n")
print(np.split(a6,[3,6]),"\n")#Split index 0 to 3(3 excluded) then split index 3 to 6(6 excluded) then the remaining
print(np.split(a6,[6,15]))
#If put more index then the available value then it will create seperate blank array for the remaining.

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])] 

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([], dtype=int64)]


In [12]:
#Horizontal and vertical split

In [13]:
a7 = np.arange(1,17).reshape(4,4)
print(a7,"\n")
print(np.hsplit(a7,2),"\n")# use for horizontal equal split. Depends the no of splits wants to do. Here its 2
print(np.hsplit(a7,[3]),"\n")#Horizontal split index 0 to 3(3 excluded) then split the remaining
print(np.hsplit(a7,[3,7]))
#If put more index then the available value then it will create seperate blank array for the remaining.
print(np.hsplit(a7,3),"\n")# Failed because 4*4 array can't be split in 3 equal entities

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])] 

[array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]]), array([[ 4],
       [ 8],
       [12],
       [16]])] 

[array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]]), array([[ 4],
       [ 8],
       [12],
       [16]]), array([], shape=(4, 0), dtype=int64)]


ValueError: array split does not result in an equal division

In [14]:
a8 = np.arange(1,17).reshape(4,4)
print(a8,"\n")
print(np.vsplit(a8,2),"\n")# use for horizontal equal split. Depends the no of splits wants to do. Here its 2
print(np.vsplit(a8,[3]),"\n")#Horizontal split index 0 to 3(3 excluded) then split the remaining
print(np.vsplit(a8,[3,7]))
#If put more index then the available value then it will create seperate blank array for the remaining.
print(np.vsplit(a8,3),"\n")# Failed because 4*4 array can't be split in 3 equal entities

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])] 

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])] 

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([], shape=(0, 4), dtype=int64)]


ValueError: array split does not result in an equal division

In [15]:
#2D split without hsplit and vsplit. With axis

In [16]:
print(a8,"\n")
print(np.split(a8,2,axis = 0),"\n")#Use for vertical equal split. Depends the no of splits wants to do. Here its 2
print(np.split(a8,2,axis = 1),"\n")#Use for horizontal equal split. Depends the no of splits wants to do. Here its 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])] 

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])] 



In [17]:
print(np.split(a8,[3],axis = 0),"\n")#Vertical split index 0 to 3(3 excluded) then split the remaining
print(np.split(a8,[3,7],axis = 1))# Horizontal
#If put more index then the available value then it will create seperate blank array for the remaining.

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])] 

[array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]]), array([[ 4],
       [ 8],
       [12],
       [16]]), array([], shape=(4, 0), dtype=int64)]


In [18]:
#Stacking

In [31]:
a9 = np.arange(5)
a10 = np.arange(5)
print(a9,a10,"\n")
print(np.vstack((a9,a10)),"\n")#Vertical stacking
print(np.hstack((a9,a10)))#Horizantal stacking

[0 1 2 3 4] [0 1 2 3 4] 

[[0 1 2 3 4]
 [0 1 2 3 4]] 

[0 1 2 3 4 0 1 2 3 4]


In [40]:
b1 = np.arange(1,5).reshape(2,2)
print(b1,"\n")
print(np.vstack((b1,b1,b1,b1)),"\n")
print(np.vstack([b1,b1,b1,b1]),"\n")
print(np.hstack([b1,b1,b1,b1]),"\n")
print(np.hstack((b1,b1,b1,b1)))

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]] 

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]] 

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


In [42]:
#Concatenate

In [50]:
b2 = np.arange(1,13)
print(b2,"\n")
np.concatenate([b2,b2,b2])#1D array Concatenate always works in horizantal

[ 1  2  3  4  5  6  7  8  9 10 11 12] 



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12])

In [58]:
b3 = np.arange(1,13).reshape(1,12)# For 2D array it works both ways according to the axis input.
print(b3,"\n")
print(np.concatenate([b3,b3,b3],axis = 1),"\n")
np.concatenate([b3,b3,b3],axis = 0)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12
   1  2  3  4  5  6  7  8  9 10 11 12]] 



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [24]:
#Broadcasting Rules:
#For each dimension ( going from right side)
#1. The size of each dimension should be same OR
#2. The size of one dimension should be 1
#Rule 1 : If two array differ in the number of dimensions, the shape of one with fewer dimensions is padded with ones on its leading( Left Side).
#Rule 2 : If the shape of two arrays doesnt match in any dimensions, the array with shape equal to 1 is stretched to match the other shape.
#Rule 3 : If in any dimesion the sizes disagree and neither equal to 1 , then Error is raised.

In [21]:
m=np.array([10,20,30,40])
n=np.array([1,2,3])
print(m)
print(n)
print(m.shape)
print(n.shape)
print(m.ndim)
print(n.ndim)

[10 20 30 40]
[1 2 3]
(4,)
(3,)
1
1


In [22]:
print(m+n)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [25]:
m=np.arange(1,7).reshape((3,2))
n=np.array([10,20])
print(m)
print(n)
print(m.shape)
print(n.shape)
print(m.ndim)
print(n.ndim)

[[1 2]
 [3 4]
 [5 6]]
[10 20]
(3, 2)
(2,)
2
1


In [26]:
m+n

array([[11, 22],
       [13, 24],
       [15, 26]])

In [27]:
m=np.array([[1,2,3]])
n=np.array([[10],[20],[30]])
print(m)
print(n)
print(m.shape)
print(n.shape)
print(m.ndim)
print(n.ndim)

[[1 2 3]]
[[10]
 [20]
 [30]]
(1, 3)
(3, 1)
2
2


In [28]:
m+n

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])