In [1]:
!pip install numpy

In [54]:
import numpy as np

In [55]:
a1 = [1,2,3,4,5,6,7,8,9]
a2 = np.array(a1)
print(a2*4)

[ 4  8 12 16 20 24 28 32 36]


In [56]:
a3 = np.arange(100)
print(a3*2)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [60]:
%timeit a3*2

694 ns ± 11.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [61]:
a2.ndim

1

In [62]:
a2.shape

(9,)

In [63]:
a3.shape

(100,)

In [64]:
a4 = np.arange(2,51,2)
print(a4)
a5 = np.arange(50,1,-2)
print(a5)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


In [65]:
a6 = np.linspace(0,10,50)
print(a6)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [66]:
print(type(a6))
print(a2.dtype)

<class 'numpy.ndarray'>
int64


In [67]:
c = [1,2,3,4,5,6,'mrunmay']
a7 = np.array(c)
print(a7)

['1' '2' '3' '4' '5' '6' 'mrunmay']


In [68]:
a8 = np.array([2,3,4,5],dtype = "float64")
print(a8)

[2. 3. 4. 5.]


In [69]:
a9 = np.array([10,100])
print(a9**10)#memory limit

[        10000000000 7766279631452241920]


In [82]:
d = [[1,3,5],[2,4,6]]
b1 = np.array(d)
print(b1*2)
print(b1.ndim)
print(b1.shape)#row,col
print(type(b1))
print(b1.dtype)

[[ 2  6 10]
 [ 4  8 12]]
2
(2, 3)
<class 'numpy.ndarray'>
int64


In [86]:
b2 = np.arange(1,13,1)
print(b2)
print(b2.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [87]:
print(np.arange(1,50,1).reshape(7,7))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [94]:
b3 = np.arange(1,17,1)
b3.reshape(-1,4)#to get the rows same for col (4,-1) -1 if you dont know any one of them.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [141]:
b4 = np.arange(1,13,1).reshape(3,4)
print(b4,"\n")
print(b4.T)#For transverse means change row to col and col to row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [140]:
print(b4,"\n")
print(b4.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [102]:
print(b4)#Not change the original value
print(b4[1][2])#Row and col simultineously
print(b4[2][3])
print(b4[1,0])#Can be written like this

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
12
5


In [139]:
b5 = np.zeros(3)
print(b5,"\n")
b6 = np.zeros(3,dtype= "int64")
print(b6)

[0. 0. 0.] 

[0 0 0]


In [137]:
b7 = np.zeros(5)
print(b7,"\n")
b8 = np.zeros((3,3), dtype = "int64")
print(b8)

[0. 0. 0. 0. 0.] 

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [119]:
b9 = np.ones((3,4))
print(b9)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [134]:
c1 = np.full((3,4),7)
print(c1,"\n")
c2 = np.full((4,5),2.9)
print(c2)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] 

[[2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]
 [2.9 2.9 2.9 2.9 2.9]]


In [144]:
c3 = np.diag([0,1,2,3,4,5,6,7,8,9])
print(c3)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [147]:
c4 = np.identity(8)
print(c4)#Prints all 1 for matrix size k*k

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [150]:
c5 = np.array([1,2,3,4,5,6,7,8,9])
print(c5[0:9:2],"\n")
print(c5[[0,2,4,6,8]])#Both are same

[1 3 5 7 9] 

[1 3 5 7 9]


In [155]:
c6 = np.arange(1,10).reshape(3,3)
print(c6,"\n")
print(c6[[0,0,0],[1,2,0]])#First list row and 2nd list col

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[2 3 1]


In [161]:
print(c6,"\n")
print(c6[::-1],"\n")
print(c6[:2,:],"\n")#Two rowa and all col
print(c6[:,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[7 8 9]
 [4 5 6]
 [1 2 3]] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [4 5]
 [7 8]]


In [166]:
print(c6[1,:2],"\n")
print(c6[:,(0,2)])

[4 5] 

[[1 3]
 [4 6]
 [7 9]]


In [188]:
c7 = np.arange(9,0,-1).reshape(3,3)
print(c7,"\n")
c7[0,2] = 33
print(c7)

[[9 8 7]
 [6 5 4]
 [3 2 1]] 

[[ 9  8 33]
 [ 6  5  4]
 [ 3  2  1]]


In [189]:
c7 = np.arange(9,0,-1).reshape(3,3)
print(c7,"\n")
c7[0:2:1] = 77
print(c7,"\n")

[[9 8 7]
 [6 5 4]
 [3 2 1]] 

[[77 77 77]
 [77 77 77]
 [ 3  2  1]] 



In [193]:
c7 = np.arange(9,0,-1).reshape(3,3)
print(c7,"\n")
c7[:2] = 77
print(c7)

[[9 8 7]
 [6 5 4]
 [3 2 1]] 

[[77 77 77]
 [77 77 77]
 [ 3  2  1]]
